remote_theme: pmarsceill/just-the-docs

plugins:
  - jekyll-remote-theme

title: Beemo Docs
email: ayu@ayu.dev
description: Beemo is a free antispam Discord Bot that can stop userbot raids against your server.
github_username: AyuAi

aux_links:
  "Go to Beemo.gg":
    - "https://beemo.gg/"
    
color_scheme: dark

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/AyuAi/beemo-docs"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"
